{{- $component_type := "blms-be-gpu" }}
{{- with (index .Values $component_type) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      nodeName: node4
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      containers:
        - name: {{ .name }}
          image: {{ $.Values.imageRepository }}/{{ .image }}
          {{- if .envFrom }}
          envFrom:
            {{- toYaml .envFrom | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .port }}
          resources:
            limits:
              nvidia.com/gpu: {{ .gpu_count }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
  selector:
    app: {{ .name }}
{{- end }}