apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeName: node4
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      containers:
        - name: ollama
          image: ollama/ollama
          command:
            - "ollama run llama3"
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 11434
  selector:
    app: ollama
---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: ollama
#   namespace: blms
#   annotations:
#     kubernetes.io/ingress.class: traefik-external
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`www.blms.transceiver.api.local.example.com`)
#       kind: Rule
#       services:
#         - name: ollama-service
#           port: 80
#     - match: Host(`blms.transceiver.api.local.example.com`)
#       kind: Rule
#       services:
#         - name: ollama-service
#           port: 80
#       middlewares:
#         - name: blms-headers
# tls:
#   secretName: local-example-com-tls
